# Generated by Django 5.1.6 on 2025-04-07 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicativo', '0008_alter_usuarios_imagem_capa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='imagem_capa',
            field=models.ImageField(blank=True, default='capa/fundo.png', null=True, upload_to='capa/'),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='imagem_perfil',
            field=models.ImageField(blank=True, default='perfil/profile_icon.png', null=True, upload_to='perfil/'),
        ),
    ]
