# Generated by Django 5.1.6 on 2025-04-08 14:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicativo', '0009_alter_usuarios_imagem_capa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='turma',
            name='sala',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Aplicativo.sala'),
            preserve_default=False,
        ),
    ]
