# Generated by Django 5.1.6 on 2025-04-08 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicativo', '0010_turma_sala'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turma',
            name='professor',
        ),
    ]
