# Generated by Django 5.1.6 on 2025-04-09 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicativo', '0011_remove_turma_professor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='escola',
            name='sala',
        ),
    ]
