# Generated by Django 5.1.6 on 2025-04-10 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicativo', '0012_remove_escola_sala'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='imagem_capa',
            field=models.ImageField(blank=True, default='capa/fundo.png', max_length=255, null=True, upload_to='capa/'),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='imagem_perfil',
            field=models.ImageField(blank=True, default='perfil/profile_icon.png', max_length=255, null=True, upload_to='perfil/'),
        ),
    ]
