# Generated by Django 4.2.20 on 2025-03-28 23:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Usuarios",
            fields=[
                ("usu_codigo", models.AutoField(primary_key=True, serialize=False)),
                (
                    "usu_nome",
                    models.CharField(max_length=45, verbose_name="Nome de Usuário"),
                ),
                (
                    "usu_email",
                    models.EmailField(
                        max_length=45, unique=True, verbose_name="E-mail"
                    ),
                ),
            ],
            options={
                "db_table": "usuarios",
            },
        ),
        migrations.CreateModel(
            name="Tarefas",
            fields=[
                ("tar_codigo", models.AutoField(primary_key=True, serialize=False)),
                (
                    "tar_descricao",
                    models.CharField(max_length=45, verbose_name="Descrição da Tarefa"),
                ),
                ("tar_setor", models.CharField(max_length=45, verbose_name="Setor")),
                (
                    "tar_prioridade",
                    models.CharField(
                        choices=[
                            ("alta", "Alta"),
                            ("media", "Média"),
                            ("baixa", "Baixa"),
                        ],
                        default="media",
                        max_length=6,
                        verbose_name="Prioridade",
                    ),
                ),
                (
                    "tar_status",
                    models.CharField(
                        choices=[
                            ("pendente", "Pendente"),
                            ("em_progresso", "Em Progresso"),
                            ("concluida", "Concluída"),
                        ],
                        default="pendente",
                        max_length=15,
                        verbose_name="Status",
                    ),
                ),
                ("tar_data", models.DateField(verbose_name="Data")),
                (
                    "usu_codigo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="aplicativo.usuarios",
                        verbose_name="Usuário",
                    ),
                ),
            ],
            options={
                "db_table": "tarefas",
            },
        ),
    ]
