# Generated by Django 5.1.6 on 2025-03-24 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicativo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='turma',
            name='tur_matricula',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
