# Generated by Django 4.2.20 on 2025-03-07 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Aplicativo", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usuarios",
            name="usu_email",
            field=models.CharField(max_length=45, verbose_name="Email"),
        ),
        migrations.AlterField(
            model_name="usuarios",
            name="usu_home",
            field=models.CharField(max_length=45, verbose_name="Nome de Usuário"),
        ),
        migrations.AlterField(
            model_name="usuarios",
            name="usu_senha",
            field=models.CharField(max_length=45, verbose_name="Senha"),
        ),
        migrations.AlterField(
            model_name="usuarios",
            name="usu_tipo",
            field=models.CharField(
                choices=[("professor", "Professor"), ("admin", "Administrador")],
                max_length=45,
                verbose_name="Cadastrar Como",
            ),
        ),
    ]
