# Generated by Django 4.2.20 on 2025-03-10 22:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "Aplicativo",
            "0002_alter_usuarios_usu_email_alter_usuarios_usu_home_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Evento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("eve_nome", models.CharField(max_length=45)),
                ("eve_descricao", models.CharField(max_length=1000)),
                ("eve_data", models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name="Professor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Turma",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tur_home_aluno", models.CharField(max_length=45)),
                ("tur_presenca", models.CharField(max_length=45)),
                (
                    "professor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Aplicativo.professor",
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="professores",
            name="Usuarios_idUsuarios",
        ),
        migrations.RemoveField(
            model_name="turmas",
            name="Professores_idProfessores",
        ),
        migrations.RenameField(
            model_name="escola",
            old_name="Usuarios_idUsuarios",
            new_name="usuario",
        ),
        migrations.RenameField(
            model_name="sala",
            old_name="Escola_idEscola",
            new_name="escola",
        ),
        migrations.AlterField(
            model_name="usuarios",
            name="usu_email",
            field=models.CharField(max_length=45, unique=True, verbose_name="Email"),
        ),
        migrations.AlterField(
            model_name="usuarios",
            name="usu_tipo",
            field=models.CharField(
                choices=[
                    ("professor", "Professor"),
                    ("administrador", "Administrador"),
                ],
                max_length=15,
                verbose_name="Cadastrar Como",
            ),
        ),
        migrations.DeleteModel(
            name="Eventos",
        ),
        migrations.DeleteModel(
            name="Professores",
        ),
        migrations.DeleteModel(
            name="Turmas",
        ),
        migrations.AddField(
            model_name="professor",
            name="usuario",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="Aplicativo.usuarios"
            ),
        ),
        migrations.AddField(
            model_name="evento",
            name="sala",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="Aplicativo.sala",
            ),
        ),
        migrations.AddField(
            model_name="evento",
            name="turma",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="Aplicativo.turma",
            ),
        ),
    ]
