# Generated by Django 5.1.6 on 2025-03-24 14:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicativo', '0002_turma_tur_matricula'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='escola',
            field=models.ManyToManyField(blank=True, related_name='usuarios_associados', to='Aplicativo.escola'),
        ),
        migrations.AlterField(
            model_name='escola',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escolas', to=settings.AUTH_USER_MODEL),
        ),
    ]
