# Generated by Django 4.2.20 on 2025-03-11 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Aplicativo", "0003_evento_professor_turma_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usuarios",
            name="usu_email",
            field=models.CharField(max_length=100, unique=True, verbose_name="Email"),
        ),
        migrations.AlterField(
            model_name="usuarios",
            name="usu_home",
            field=models.CharField(max_length=100, verbose_name="Nome de Usuário"),
        ),
        migrations.AlterField(
            model_name="usuarios",
            name="usu_senha",
            field=models.CharField(max_length=128),
        ),
    ]
