# Generated by Django 5.1.6 on 2025-03-24 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicativo', '0003_usuarios_escola_alter_escola_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='escola',
            name='usuario',
        ),
    ]
