# Generated by Django 5.1.6 on 2025-03-24 14:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicativo', '0004_remove_escola_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuarios',
            name='escola',
        ),
        migrations.AddField(
            model_name='escola',
            name='sala',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='escola',
            name='usuarios_associados',
            field=models.ManyToManyField(related_name='escolas_associadas_escola', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='usuarios',
            name='escolas',
            field=models.ManyToManyField(blank=True, related_name='usuarios_associados_usuario', to='Aplicativo.escola'),
        ),
        migrations.AlterField(
            model_name='escola',
            name='codigo_unico',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='escola',
            name='esc_desc',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='escola',
            name='esc_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='evento',
            name='sala',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='Aplicativo.sala'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='turma',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='Aplicativo.turma'),
        ),
        migrations.AlterField(
            model_name='professor',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='professores', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sala',
            name='escola',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salas', to='Aplicativo.escola'),
        ),
        migrations.AlterField(
            model_name='turma',
            name='professor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turmas', to='Aplicativo.professor'),
        ),
    ]
