# Generated by Django 4.2.20 on 2025-03-11 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "Aplicativo",
            "0004_alter_usuarios_usu_email_alter_usuarios_usu_home_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="usuarios",
            name="usu_email",
            field=models.EmailField(max_length=100, unique=True, verbose_name="Email"),
        ),
    ]
