# Generated by Django 5.1.6 on 2025-03-26 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicativo', '0005_remove_usuarios_escola_escola_sala_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='escola',
            name='codigo_unico',
        ),
        migrations.AddField(
            model_name='usuarios',
            name='codigo_unico',
            field=models.CharField(default=1, max_length=8),
            preserve_default=False,
        ),
    ]
