# Generated by Django 4.2.20 on 2025-03-11 00:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("Aplicativo", "0005_alter_usuarios_usu_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="usuarios",
            name="last_login",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="usuarios",
            name="usu_email",
            field=models.CharField(max_length=100, unique=True, verbose_name="Email"),
        ),
    ]
