# Generated by Django 5.1.6 on 2025-03-27 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicativo', '0006_remove_escola_codigo_unico_usuarios_codigo_unico'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='imagem_capa',
            field=models.ImageField(blank=True, default='capa/default.jpg', null=True, upload_to='capa/'),
        ),
        migrations.AddField(
            model_name='usuarios',
            name='imagem_perfil',
            field=models.ImageField(blank=True, default='perfil/default.jpg', null=True, upload_to='perfil/'),
        ),
    ]
