# Generated by Django 4.2.20 on 2025-03-11 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Aplicativo", "0007_remove_usuarios_usu_senha_usuarios_groups_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="usuarios",
            name="groups",
        ),
        migrations.RemoveField(
            model_name="usuarios",
            name="is_superuser",
        ),
        migrations.RemoveField(
            model_name="usuarios",
            name="last_login",
        ),
        migrations.RemoveField(
            model_name="usuarios",
            name="password",
        ),
        migrations.RemoveField(
            model_name="usuarios",
            name="user_permissions",
        ),
        migrations.AddField(
            model_name="usuarios",
            name="usu_senha",
            field=models.CharField(default=1, max_length=45, verbose_name="Senha"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="usuarios",
            name="usu_email",
            field=models.CharField(max_length=45, unique=True, verbose_name="Email"),
        ),
        migrations.AlterField(
            model_name="usuarios",
            name="usu_home",
            field=models.CharField(max_length=45, verbose_name="Nome de Usuário"),
        ),
    ]
