# Generated by Django 4.2.20 on 2025-03-11 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        (
            "Aplicativo",
            "0008_remove_usuarios_groups_remove_usuarios_is_superuser_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="usuarios",
            name="usu_senha",
        ),
        migrations.AddField(
            model_name="usuarios",
            name="groups",
            field=models.ManyToManyField(
                blank=True, related_name="custom_user_groups", to="auth.group"
            ),
        ),
        migrations.AddField(
            model_name="usuarios",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="usuarios",
            name="is_staff",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="usuarios",
            name="is_superuser",
            field=models.BooleanField(
                default=False,
                help_text="Designates that this user has all permissions without explicitly assigning them.",
                verbose_name="superuser status",
            ),
        ),
        migrations.AddField(
            model_name="usuarios",
            name="last_login",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="last login"
            ),
        ),
        migrations.AddField(
            model_name="usuarios",
            name="password",
            field=models.CharField(default=1, max_length=128, verbose_name="password"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="usuarios",
            name="user_permissions",
            field=models.ManyToManyField(
                blank=True, related_name="custom_user_permissions", to="auth.permission"
            ),
        ),
        migrations.AlterField(
            model_name="usuarios",
            name="usu_email",
            field=models.EmailField(max_length=254, unique=True, verbose_name="Email"),
        ),
        migrations.AlterField(
            model_name="usuarios",
            name="usu_tipo",
            field=models.CharField(
                choices=[
                    ("professor", "Professor"),
                    ("administrador", "Administrador"),
                ],
                max_length=15,
                verbose_name="Tipo de Usuário",
            ),
        ),
    ]
