# Generated by Django 4.2.20 on 2025-03-11 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("Aplicativo", "0009_remove_usuarios_usu_senha_usuarios_groups_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usuarios",
            name="groups",
            field=models.ManyToManyField(
                blank=True, related_name="usuarios_groups", to="auth.group"
            ),
        ),
        migrations.AlterField(
            model_name="usuarios",
            name="user_permissions",
            field=models.ManyToManyField(
                blank=True, related_name="usuarios_permissions", to="auth.permission"
            ),
        ),
        migrations.AlterField(
            model_name="usuarios",
            name="usu_email",
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name="usuarios",
            name="usu_home",
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name="usuarios",
            name="usu_tipo",
            field=models.CharField(
                choices=[
                    ("professor", "Professor"),
                    ("administrador", "Administrador"),
                ],
                max_length=50,
            ),
        ),
    ]
