# Generated by Django 5.1.2 on 2025-02-11 04:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Escola',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('esc_name', models.CharField(max_length=45)),
                ('esc_desc', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Professores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usu_home', models.CharField(max_length=45)),
                ('usu_email', models.CharField(max_length=45)),
                ('usu_senha', models.CharField(max_length=45)),
                ('usu_tipo', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sal_name', models.CharField(max_length=45)),
                ('sal_desc', models.CharField(max_length=45)),
                ('sal_cod_acesso', models.CharField(max_length=6)),
                ('Escola_idEscola', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Aplicativo.escola')),
            ],
        ),
        migrations.CreateModel(
            name='Turmas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tur_home_aluno', models.CharField(max_length=45)),
                ('tur_presenca', models.CharField(max_length=45)),
                ('Professores_idProfessores', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Aplicativo.professores')),
            ],
        ),
        migrations.CreateModel(
            name='Eventos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eve_nome', models.CharField(max_length=45)),
                ('eve_descricao', models.CharField(max_length=1000)),
                ('eve_data', models.DateTimeField()),
                ('Sala_idSala', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Aplicativo.sala')),
                ('Turmas_idTurmas', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Aplicativo.turmas')),
            ],
        ),
        migrations.AddField(
            model_name='professores',
            name='Usuarios_idUsuarios',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Aplicativo.usuarios'),
        ),
        migrations.AddField(
            model_name='escola',
            name='Usuarios_idUsuarios',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Aplicativo.usuarios'),
        ),
    ]
